
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Notebook notebook1;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Image image6;
	
	private global::Gtk.Button ButtonNextQuote;
	
	private global::Gtk.Label labelQuote;
	
	private global::Gtk.Label QuotesTab;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Chuck Norris");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-floppy", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 1000;
		this.DefaultHeight = 500;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Homogeneous = true;
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.image6 = new global::Gtk.Image ();
		this.image6.Name = "image6";
		this.hbox2.Add (this.image6);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.image6]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.ButtonNextQuote = new global::Gtk.Button ();
		this.ButtonNextQuote.CanFocus = true;
		this.ButtonNextQuote.Name = "ButtonNextQuote";
		this.ButtonNextQuote.UseUnderline = true;
		this.ButtonNextQuote.Label = global::Mono.Unix.Catalog.GetString ("Next Quote");
		this.hbox2.Add (this.ButtonNextQuote);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.ButtonNextQuote]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.labelQuote = new global::Gtk.Label ();
		this.labelQuote.Name = "labelQuote";
		this.labelQuote.LabelProp = global::Mono.Unix.Catalog.GetString ("Quote Here...");
		this.vbox1.Add (this.labelQuote);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.labelQuote]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.notebook1.Add (this.vbox1);
		// Notebook tab
		this.QuotesTab = new global::Gtk.Label ();
		this.QuotesTab.Name = "QuotesTab";
		this.QuotesTab.LabelProp = global::Mono.Unix.Catalog.GetString ("Quotes");
		this.notebook1.SetTabLabel (this.vbox1, this.QuotesTab);
		this.QuotesTab.ShowAll ();
		this.Add (this.notebook1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.ButtonNextQuote.Clicked += new global::System.EventHandler (this.NextQuoteButtonClicked);
	}
}
