
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Notebook notebook1;
	
	private global::Gtk.Fixed fixed2;
	
	private global::Gtk.Label QuotesTab;
	
	private global::Gtk.Label GraphTab;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Chuck Norris");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 1000;
		this.DefaultHeight = 500;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.notebook1.Add (this.fixed2);
		global::Gtk.Notebook.NotebookChild w1 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.fixed2]));
		w1.TabFill = false;
		// Notebook tab
		this.QuotesTab = new global::Gtk.Label ();
		this.QuotesTab.Name = "QuotesTab";
		this.QuotesTab.LabelProp = global::Mono.Unix.Catalog.GetString ("Quotes");
		this.notebook1.SetTabLabel (this.fixed2, this.QuotesTab);
		this.QuotesTab.ShowAll ();
		// Notebook tab
		global::Gtk.Label w2 = new global::Gtk.Label ();
		w2.Visible = true;
		this.notebook1.Add (w2);
		this.GraphTab = new global::Gtk.Label ();
		this.GraphTab.Name = "GraphTab";
		this.GraphTab.LabelProp = global::Mono.Unix.Catalog.GetString ("Graph");
		this.notebook1.SetTabLabel (w2, this.GraphTab);
		this.GraphTab.ShowAll ();
		this.Add (this.notebook1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
